export enum Focus {
  TO_TRAIN = 'TO_TRAIN',
  PERSONAL_TRAINER = 'PERSONAL_TRAINER',
  SPORT_COACH = 'SPORT_COACH',
  GYM_MANAGER = 'GYM_MANAGER',
  OWNER = 'OWNER',
  HEALTH_PROFESSIONAL = 'HEALTH_PROFESSIONAL',
}
